/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package edu.hdsb.gwss.spencercook.ics3u.u5;

/**
 *
 * @author 1cookspe
 */
public class ReduceFraction extends javax.swing.JFrame {

    /**
     * Creates new form ReduceFraction
     */
    public ReduceFraction() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        title = new javax.swing.JLabel();
        instructions = new javax.swing.JLabel();
        numeratorLabel = new javax.swing.JLabel();
        denominatorLabel = new javax.swing.JLabel();
        numerator = new javax.swing.JTextField();
        demoninator = new javax.swing.JTextField();
        results = new javax.swing.JLabel();
        calculateFraction = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        title.setForeground(new java.awt.Color(153, 0, 0));
        title.setText("Reduce Fraction");

        instructions.setText("This program will reduce a fraction into its lowest terms.");

        numeratorLabel.setText("Enter the Numerator:");

        denominatorLabel.setText("Enter the Denominator:");

        results.setText("55/125 can be reduced to 11/25");

        calculateFraction.setText("Calculate!");
        calculateFraction.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                calculateFractionActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(164, 164, 164)
                .addComponent(title)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(81, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                            .addComponent(instructions)
                            .addGap(81, 81, 81))
                        .addGroup(layout.createSequentialGroup()
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(calculateFraction)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(numeratorLabel)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(numerator, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(denominatorLabel)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(demoninator, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addGap(117, 117, 117)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(results)
                        .addGap(135, 135, 135))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addComponent(title)
                .addGap(18, 18, 18)
                .addComponent(instructions, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(36, 36, 36)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(numerator, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(numeratorLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(denominatorLabel)
                    .addComponent(demoninator, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 20, Short.MAX_VALUE)
                .addComponent(calculateFraction)
                .addGap(18, 18, 18)
                .addComponent(results)
                .addGap(53, 53, 53))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void calculateFractionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_calculateFractionActionPerformed
        //Variables
        int topNumber = Integer.parseInt(numerator.getText());
        int bottomNumber = Integer.parseInt(demoninator.getText());
         
         //Calculate reduced fraction
         int reducedNumerator = topNumber / calculateGreatestCommonDivisor(topNumber, bottomNumber);
         int reducedDenominator = bottomNumber / calculateGreatestCommonDivisor(topNumber, bottomNumber);
         
         if (reducedNumerator == topNumber && bottomNumber == reducedDenominator) {
             results.setText("This fraction cannot be reduced. Try another one?");
         } else {
             results.setText("" + topNumber + " / " + bottomNumber + " can be simplied into " + reducedNumerator + " / " + reducedDenominator + ".");
         }
         
//        }
    }//GEN-LAST:event_calculateFractionActionPerformed
    
//    public boolean checkIfFractionIsReducable(double numerator, double demoninator) {
//        if (numerator % 2 == 0 && demoninator % 2 == 0) {
//            return true;
//        } else {
//            if (numerator % 5 == 0 && denominator )
//        }
//        return false;
//    }
    
    public int calculateGreatestCommonDivisor(int numerator, int denominator) {
        //Variables
        int smallestNumber;
        int greatestCommonFactor = 1;
        
        if (numerator < denominator) {
            smallestNumber = numerator;
        } else if (numerator > denominator) {
            smallestNumber = denominator;
        } else {
            smallestNumber = numerator;
        }
        
        for (int i = 2; i <= smallestNumber; i++) {
            if (numerator % i == 0 && denominator % i == 0) {
                greatestCommonFactor = i;
            }
        }
        
        return greatestCommonFactor;
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ReduceFraction.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ReduceFraction.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ReduceFraction.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ReduceFraction.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ReduceFraction().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton calculateFraction;
    private javax.swing.JTextField demoninator;
    private javax.swing.JLabel denominatorLabel;
    private javax.swing.JLabel instructions;
    private javax.swing.JTextField numerator;
    private javax.swing.JLabel numeratorLabel;
    private javax.swing.JLabel results;
    private javax.swing.JLabel title;
    // End of variables declaration//GEN-END:variables
}
