/* Name: Spencer Cook
 * Date: November 11, 2014
 * Version: v0
 * Description:
 This program stores the temperatures in an array and displays them to the user
 */
package edu.hdsb.gwss.spencercook.ics3u.u6;

import javax.swing.JOptionPane;

/**
 *
 * @author 1cookspe
 */
public class Temperatures extends javax.swing.JFrame {

    //Global variables

    int[] temperatures = new int[7];
    String[] dayNames = {"Sunday", "Monday", "Tuesday", "Wednesday", "Thursday", "Friday", "Saturday"};
    int dayTemperature = 1;

    /**
     * Creates new form Temperatures
     */
    public Temperatures() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        dailyTemperatures = new javax.swing.JLabel();
        inputTemperature = new javax.swing.JLabel();
        temperatureText = new javax.swing.JTextField();
        submitTemperature = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        displayOfTemperature = new javax.swing.JTextArea();
        daysInputted = new javax.swing.JLabel();
        averageTemperature = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        dailyTemperatures.setText("Daily Temperatures!");

        inputTemperature.setText("Input the Temperature for Sunday (in C):");

        submitTemperature.setText("Submit Temperature");
        submitTemperature.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                submitTemperatureActionPerformed(evt);
            }
        });

        displayOfTemperature.setColumns(20);
        displayOfTemperature.setRows(5);
        jScrollPane1.setViewportView(displayOfTemperature);

        daysInputted.setText("Days Inputted:");

        averageTemperature.setForeground(new java.awt.Color(255, 51, 0));
        averageTemperature.setText("Average Temperature:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(118, 118, 118)
                        .addComponent(dailyTemperatures))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(59, 59, 59)
                                .addComponent(inputTemperature))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(daysInputted)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(submitTemperature)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(temperatureText, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(38, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(averageTemperature)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(34, 34, 34))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(dailyTemperatures)
                .addGap(29, 29, 29)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(inputTemperature)
                    .addComponent(temperatureText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(submitTemperature)
                    .addComponent(daysInputted))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 155, Short.MAX_VALUE)
                        .addContainerGap())
                    .addGroup(layout.createSequentialGroup()
                        .addGap(27, 27, 27)
                        .addComponent(averageTemperature)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void submitTemperatureActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_submitTemperatureActionPerformed
        if (!temperatureText.getText().equals("")) {
            temperatures[dayTemperature - 1] = Integer.parseInt(temperatureText.getText());
            displayOfTemperature.setText(displayOfTemperature.getText() + "" + dayNames[dayTemperature - 1] + ": " + temperatures[dayTemperature - 1] + "\n");
            displayOfTemperature.setEditable(false);

            daysInputted.setText("Days Inputted: " + dayTemperature);

            temperatureText.setText("");
            inputTemperature.setText("Input the Temperature for " + dayNames[dayTemperature - 1] + " (in Cº).");

            dayTemperature++;
            if (dayTemperature == 8) {
                JOptionPane.showMessageDialog(this, "You have inputted temperatures for the week.");
                temperatureText.setEditable(false);
                temperatureText.setEnabled(false);
                inputTemperature.setText("All days have been input!");
                submitTemperature.setEnabled(false);
            }
            
            averageTemperature.setText("Average Temperature: " + ArrayUtil.calculateNonZeroAverage(temperatures) + " Cº");
        } else {
            JOptionPane.showMessageDialog(this, "Please input a valid temperature!");
        }
    }//GEN-LAST:event_submitTemperatureActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Temperatures.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Temperatures.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Temperatures.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Temperatures.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Temperatures().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel averageTemperature;
    private javax.swing.JLabel dailyTemperatures;
    private javax.swing.JLabel daysInputted;
    private javax.swing.JTextArea displayOfTemperature;
    private javax.swing.JLabel inputTemperature;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton submitTemperature;
    private javax.swing.JTextField temperatureText;
    // End of variables declaration//GEN-END:variables
}
