/* Name: Spencer Cook
 * Date: December 17, 2014
 * Version: v0
 * Description:
 This program sorts the movies from an XML file
 */
package edu.hdsb.gwss.spencercook.ics3u.u7;

import java.io.File;
import java.io.FileNotFoundException;
import java.io.PrintWriter;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.DefaultListModel;
import nu.xom.Builder;
import nu.xom.Document;
import nu.xom.Element;
import nu.xom.Elements;

/**
 *
 * @author 1cookspe
 */
public class SortedMovies extends javax.swing.JFrame {

    /**
     *
     * Creates new form SortedMovies
     */
    public SortedMovies() {
        initComponents();
        importData();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane20 = new javax.swing.JScrollPane();
        jList10 = new javax.swing.JList();
        sortedMoviesLabel = new javax.swing.JLabel();
        importListButton = new javax.swing.JButton();
        actionLabel = new javax.swing.JLabel();
        mysteryLabel = new javax.swing.JLabel();
        comedyLabel = new javax.swing.JLabel();
        jScrollPane4 = new javax.swing.JScrollPane();
        actionList = new javax.swing.JList();
        jScrollPane5 = new javax.swing.JScrollPane();
        mysteryList = new javax.swing.JList();
        jScrollPane6 = new javax.swing.JScrollPane();
        comedyList = new javax.swing.JList();
        dramaLabel = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        dramaList = new javax.swing.JList();
        thrillerLabel = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        sciFiList = new javax.swing.JList();
        horrorLabel = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        horrorList = new javax.swing.JList();
        romanticLabel = new javax.swing.JLabel();
        jScrollPane7 = new javax.swing.JScrollPane();
        romanticList = new javax.swing.JList();
        classicLabel = new javax.swing.JLabel();
        jScrollPane8 = new javax.swing.JScrollPane();
        classicList = new javax.swing.JList();
        animatedLabel = new javax.swing.JLabel();
        jScrollPane9 = new javax.swing.JScrollPane();
        animatedList = new javax.swing.JList();
        sciFiLabel = new javax.swing.JLabel();
        jScrollPane10 = new javax.swing.JScrollPane();
        thrillerList = new javax.swing.JList();
        mainMenuButton = new javax.swing.JButton();
        addNewMovieButton = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane11 = new javax.swing.JScrollPane();
        actionRatingList = new javax.swing.JList();
        actionRatingLabel = new javax.swing.JLabel();
        jScrollPane12 = new javax.swing.JScrollPane();
        horrorRatingList = new javax.swing.JList();
        horrorRatingLabel = new javax.swing.JLabel();
        jScrollPane13 = new javax.swing.JScrollPane();
        mysteryRatingList = new javax.swing.JList();
        jScrollPane14 = new javax.swing.JScrollPane();
        comedyRatingList = new javax.swing.JList();
        jScrollPane15 = new javax.swing.JScrollPane();
        dramaRatingList = new javax.swing.JList();
        jScrollPane16 = new javax.swing.JScrollPane();
        animatedRatingList = new javax.swing.JList();
        dramaRatingLabel = new javax.swing.JLabel();
        mysteryRatingLabel = new javax.swing.JLabel();
        comedyRatingLabel = new javax.swing.JLabel();
        animatedRatingLabel = new javax.swing.JLabel();
        jScrollPane17 = new javax.swing.JScrollPane();
        romanticRatingList = new javax.swing.JList();
        romanticRatingLabel = new javax.swing.JLabel();
        classicRatingLabel = new javax.swing.JLabel();
        jScrollPane18 = new javax.swing.JScrollPane();
        classicRatingList = new javax.swing.JList();
        jScrollPane19 = new javax.swing.JScrollPane();
        thrillerRatingList = new javax.swing.JList();
        jScrollPane21 = new javax.swing.JScrollPane();
        sciFiRatingList = new javax.swing.JList();
        thrillerRatingLabel = new javax.swing.JLabel();
        sciFiRatingLabel = new javax.swing.JLabel();

        jList10.setModel(new javax.swing.AbstractListModel() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public Object getElementAt(int i) { return strings[i]; }
        });
        jScrollPane20.setViewportView(jList10);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(1000, 650));

        sortedMoviesLabel.setFont(new java.awt.Font("Bodoni MT Black", 0, 24)); // NOI18N
        sortedMoviesLabel.setText("Sorted Movies");

        importListButton.setFont(new java.awt.Font("Swis721 BlkEx BT", 0, 18)); // NOI18N
        importListButton.setText("Import List");
        importListButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                importListButtonActionPerformed(evt);
            }
        });

        actionLabel.setFont(new java.awt.Font("Impact", 0, 18)); // NOI18N
        actionLabel.setText("Action");

        mysteryLabel.setFont(new java.awt.Font("Impact", 0, 18)); // NOI18N
        mysteryLabel.setText("Mystery");

        comedyLabel.setFont(new java.awt.Font("Impact", 0, 18)); // NOI18N
        comedyLabel.setText("Comedy");

        jScrollPane4.setViewportView(actionList);

        jScrollPane5.setViewportView(mysteryList);

        jScrollPane6.setViewportView(comedyList);

        dramaLabel.setFont(new java.awt.Font("Impact", 0, 18)); // NOI18N
        dramaLabel.setText("Drama");

        jScrollPane1.setViewportView(dramaList);

        thrillerLabel.setFont(new java.awt.Font("Impact", 0, 18)); // NOI18N
        thrillerLabel.setText("Thriller");

        jScrollPane2.setViewportView(sciFiList);

        horrorLabel.setFont(new java.awt.Font("Impact", 0, 18)); // NOI18N
        horrorLabel.setText("Horror");

        jScrollPane3.setViewportView(horrorList);

        romanticLabel.setFont(new java.awt.Font("Impact", 0, 18)); // NOI18N
        romanticLabel.setText("Romantic");

        jScrollPane7.setViewportView(romanticList);

        classicLabel.setFont(new java.awt.Font("Impact", 0, 18)); // NOI18N
        classicLabel.setText("Classic");

        jScrollPane8.setViewportView(classicList);

        animatedLabel.setFont(new java.awt.Font("Impact", 0, 18)); // NOI18N
        animatedLabel.setText("Animated");

        jScrollPane9.setViewportView(animatedList);

        sciFiLabel.setFont(new java.awt.Font("Impact", 0, 18)); // NOI18N
        sciFiLabel.setText("Sci-Fi");

        jScrollPane10.setViewportView(thrillerList);

        mainMenuButton.setFont(new java.awt.Font("FreesiaUPC", 1, 24)); // NOI18N
        mainMenuButton.setText("Main Menu");
        mainMenuButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mainMenuButtonActionPerformed(evt);
            }
        });

        addNewMovieButton.setFont(new java.awt.Font("FreesiaUPC", 1, 24)); // NOI18N
        addNewMovieButton.setText("Add New Movie");
        addNewMovieButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addNewMovieButtonActionPerformed(evt);
            }
        });

        jScrollPane11.setViewportView(actionRatingList);

        actionRatingLabel.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        actionRatingLabel.setText("Rating");

        jScrollPane12.setViewportView(horrorRatingList);

        horrorRatingLabel.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        horrorRatingLabel.setText("Rating");

        jScrollPane13.setViewportView(mysteryRatingList);

        jScrollPane14.setViewportView(comedyRatingList);

        jScrollPane15.setViewportView(dramaRatingList);

        jScrollPane16.setViewportView(animatedRatingList);

        dramaRatingLabel.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        dramaRatingLabel.setText("Rating");

        mysteryRatingLabel.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        mysteryRatingLabel.setText("Rating");

        comedyRatingLabel.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        comedyRatingLabel.setText("Rating");

        animatedRatingLabel.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        animatedRatingLabel.setText("Rating");

        jScrollPane17.setViewportView(romanticRatingList);

        romanticRatingLabel.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        romanticRatingLabel.setText("Rating");

        classicRatingLabel.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        classicRatingLabel.setText("Rating");

        jScrollPane18.setViewportView(classicRatingList);

        jScrollPane19.setViewportView(thrillerRatingList);

        jScrollPane21.setViewportView(sciFiRatingList);

        thrillerRatingLabel.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        thrillerRatingLabel.setText("Rating");

        sciFiRatingLabel.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        sciFiRatingLabel.setText("Rating");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(8, 8, 8)
                                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(26, 26, 26)
                                .addComponent(horrorLabel)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(14, 14, 14)
                                .addComponent(horrorRatingLabel))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGap(6, 6, 6)
                                .addComponent(jScrollPane12, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(124, 124, 124)
                                .addComponent(jLabel1))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(51, 51, 51)
                                .addComponent(romanticLabel)
                                .addGap(18, 18, 18)
                                .addComponent(romanticRatingLabel)
                                .addGap(74, 74, 74)
                                .addComponent(classicLabel)
                                .addGap(18, 18, 18)
                                .addComponent(classicRatingLabel))))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(20, 20, 20)
                                .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jScrollPane11, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(24, 24, 24))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addGap(40, 40, 40)
                                .addComponent(actionLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(44, 44, 44)
                                .addComponent(actionRatingLabel)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jScrollPane7, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jScrollPane17, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addComponent(mysteryLabel)
                                        .addGap(21, 21, 21)))
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(mysteryRatingLabel)
                                    .addComponent(jScrollPane13, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(58, 58, 58)
                                .addComponent(comedyLabel)
                                .addGap(18, 18, 18)
                                .addComponent(comedyRatingLabel))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(33, 33, 33)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jScrollPane8, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jScrollPane18, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jScrollPane6, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jScrollPane14, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)))))))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(34, 34, 34)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(jScrollPane9, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jScrollPane16, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(dramaLabel)
                                    .addGap(37, 37, 37)
                                    .addComponent(dramaRatingLabel))
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(jScrollPane15, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(66, 66, 66)
                                .addComponent(thrillerLabel))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jScrollPane2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jScrollPane10, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(48, 48, 48)
                        .addComponent(animatedLabel)
                        .addGap(18, 18, 18)
                        .addComponent(animatedRatingLabel)
                        .addGap(75, 75, 75)
                        .addComponent(sciFiLabel)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(sciFiRatingLabel)
                    .addComponent(thrillerRatingLabel)
                    .addComponent(jScrollPane19, javax.swing.GroupLayout.DEFAULT_SIZE, 61, Short.MAX_VALUE)
                    .addComponent(jScrollPane21, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(341, 341, 341)
                        .addComponent(sortedMoviesLabel))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addGap(28, 28, 28)
                        .addComponent(mainMenuButton, javax.swing.GroupLayout.PREFERRED_SIZE, 169, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(importListButton)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(addNewMovieButton)
                .addGap(51, 51, 51))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(sortedMoviesLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 44, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(importListButton)
                        .addGap(41, 41, 41))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(22, 22, 22)
                                .addComponent(addNewMovieButton, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(38, 38, 38)
                                .addComponent(mainMenuButton, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel1)
                        .addGap(8, 8, 8)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(thrillerLabel)
                            .addComponent(thrillerRatingLabel))
                        .addGap(8, 8, 8)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jScrollPane10)
                            .addComponent(jScrollPane19)))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(mysteryLabel)
                            .addComponent(comedyLabel)
                            .addComponent(dramaLabel)
                            .addComponent(dramaRatingLabel)
                            .addComponent(mysteryRatingLabel)
                            .addComponent(comedyRatingLabel)
                            .addComponent(actionRatingLabel)
                            .addComponent(actionLabel))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jScrollPane13)
                            .addComponent(jScrollPane5)
                            .addComponent(jScrollPane6)
                            .addComponent(jScrollPane14)
                            .addComponent(jScrollPane1)
                            .addComponent(jScrollPane15)
                            .addComponent(jScrollPane11)
                            .addComponent(jScrollPane4))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 30, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(horrorLabel)
                    .addComponent(horrorRatingLabel)
                    .addComponent(romanticLabel)
                    .addComponent(romanticRatingLabel)
                    .addComponent(classicLabel)
                    .addComponent(classicRatingLabel)
                    .addComponent(animatedLabel)
                    .addComponent(animatedRatingLabel)
                    .addComponent(sciFiLabel)
                    .addComponent(sciFiRatingLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane12)
                    .addComponent(jScrollPane3)
                    .addComponent(jScrollPane7)
                    .addComponent(jScrollPane17)
                    .addComponent(jScrollPane8)
                    .addComponent(jScrollPane18)
                    .addComponent(jScrollPane9)
                    .addComponent(jScrollPane16)
                    .addComponent(jScrollPane2)
                    .addComponent(jScrollPane21))
                .addGap(14, 14, 14))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void importListButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_importListButtonActionPerformed
        importData();

    }//GEN-LAST:event_importListButtonActionPerformed

    public void importData() {
        File file = new File("movieMadness.xml");
        Builder builder = new Builder();

        try {
            Document movieDocument = builder.build(file);
            Element movieRoot = movieDocument.getRootElement();
            Elements movies = movieRoot.getChildElements();

            DefaultListModel actionModel = new DefaultListModel();
            DefaultListModel actionRatingModel = new DefaultListModel();
            DefaultListModel mysteryModel = new DefaultListModel();
            DefaultListModel mysteryRatingModel = new DefaultListModel();
            DefaultListModel comedyModel = new DefaultListModel();
            DefaultListModel comedyRatingModel = new DefaultListModel();
            DefaultListModel dramaModel = new DefaultListModel();
            DefaultListModel dramaRatingModel = new DefaultListModel();
            DefaultListModel thrillerModel = new DefaultListModel();
            DefaultListModel thrillerRatingModel = new DefaultListModel();
            DefaultListModel horrorModel = new DefaultListModel();
            DefaultListModel horrorRatingModel = new DefaultListModel();
            DefaultListModel romanticModel = new DefaultListModel();
            DefaultListModel romanticRatingModel = new DefaultListModel();
            DefaultListModel classicModel = new DefaultListModel();
            DefaultListModel classicRatingModel = new DefaultListModel();
            DefaultListModel animatedModel = new DefaultListModel();
            DefaultListModel animatedRatingModel = new DefaultListModel();
            DefaultListModel sciFiModel = new DefaultListModel();
            DefaultListModel sciFiRatingModel = new DefaultListModel();

            for (int i = 0; i < movies.size(); i++) {

                if (movies.get(i).getFirstChildElement("movieGenre").getValue().equals("Action")) {
                    actionModel.addElement(movies.get(i).getFirstChildElement("movieName").getValue());
                    actionRatingModel.addElement(movies.get(i).getFirstChildElement("movieRating").getValue());
                } else if (movies.get(i).getFirstChildElement("movieGenre").getValue().equals("Mystery")) {
                    mysteryModel.addElement(movies.get(i).getFirstChildElement("movieName").getValue());
                    mysteryRatingModel.addElement(movies.get(i).getFirstChildElement("movieRating").getValue());
                } else if (movies.get(i).getFirstChildElement("movieGenre").getValue().equals("Comedy")) {
                    comedyModel.addElement(movies.get(i).getFirstChildElement("movieName").getValue());
                    comedyRatingModel.addElement(movies.get(i).getFirstChildElement("movieRating").getValue());
                } else if (movies.get(i).getFirstChildElement("movieGenre").getValue().equals("Drama")) {
                    dramaModel.addElement(movies.get(i).getFirstChildElement("movieName").getValue());
                    dramaRatingModel.addElement(movies.get(i).getFirstChildElement("movieRating").getValue() + " STARS");
                } else if (movies.get(i).getFirstChildElement("movieGenre").getValue().equals("Thriller")) {
                    thrillerModel.addElement(movies.get(i).getFirstChildElement("movieName").getValue());
                    thrillerRatingModel.addElement(movies.get(i).getFirstChildElement("movieRating").getValue() + " STARS");
                } else if (movies.get(i).getFirstChildElement("movieGenre").getValue().equals("Horror")) {
                    horrorModel.addElement(movies.get(i).getFirstChildElement("movieName").getValue());
                    horrorRatingModel.addElement(movies.get(i).getFirstChildElement("movieRating").getValue());
                } else if (movies.get(i).getFirstChildElement("movieGenre").getValue().equals("Romantic")) {
                    romanticModel.addElement(movies.get(i).getFirstChildElement("movieName").getValue());
                    romanticRatingModel.addElement(movies.get(i).getFirstChildElement("movieRating").getValue());
                } else if (movies.get(i).getFirstChildElement("movieGenre").getValue().equals("Classic")) {
                    classicModel.addElement(movies.get(i).getFirstChildElement("movieName").getValue());
                    classicRatingModel.addElement(movies.get(i).getFirstChildElement("movieRating").getValue());
                } else if (movies.get(i).getFirstChildElement("movieGenre").getValue().equals("Animated")) {
                    animatedModel.addElement(movies.get(i).getFirstChildElement("movieName").getValue());
                    animatedRatingModel.addElement(movies.get(i).getFirstChildElement("movieRating").getValue());
                } else if (movies.get(i).getFirstChildElement("movieGenre").getValue().equals("Sci-Fi")) {
                    sciFiModel.addElement(movies.get(i).getFirstChildElement("movieName").getValue());
                    sciFiRatingModel.addElement(movies.get(i).getFirstChildElement("movieRating").getValue());
                }
            }

            actionList.setModel(actionModel);
            actionRatingList.setModel(actionRatingModel);
            mysteryList.setModel(mysteryModel);
            mysteryRatingList.setModel(mysteryRatingModel);
            comedyList.setModel(comedyModel);
            comedyRatingList.setModel(comedyRatingModel);
            dramaList.setModel(dramaModel);
            dramaRatingList.setModel(dramaRatingModel);
            animatedList.setModel(animatedModel);
            animatedRatingList.setModel(animatedRatingModel);
            sciFiList.setModel(sciFiModel);
            sciFiRatingList.setModel(sciFiRatingModel);
            classicList.setModel(classicModel);
            classicRatingList.setModel(classicRatingModel);
            horrorList.setModel(horrorModel);
            horrorRatingList.setModel(horrorRatingModel);
            romanticList.setModel(romanticModel);
            romanticRatingList.setModel(romanticRatingModel);
            thrillerList.setModel(thrillerModel);
            thrillerRatingList.setModel(thrillerRatingModel);

        } catch (Exception e) {
            System.err.println(e);
        }
    }


    private void mainMenuButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mainMenuButtonActionPerformed
        new MovieMenu().setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_mainMenuButtonActionPerformed

    private void addNewMovieButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addNewMovieButtonActionPerformed
        new AddMovie().setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_addNewMovieButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(SortedMovies.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(SortedMovies.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(SortedMovies.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SortedMovies.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new SortedMovies().setVisible(true);
                //new SortedMovies().setTitle("Movie Madness");
            }
        });
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel actionLabel;
    private javax.swing.JList actionList;
    private javax.swing.JLabel actionRatingLabel;
    private javax.swing.JList actionRatingList;
    private javax.swing.JButton addNewMovieButton;
    private javax.swing.JLabel animatedLabel;
    private javax.swing.JList animatedList;
    private javax.swing.JLabel animatedRatingLabel;
    private javax.swing.JList animatedRatingList;
    private javax.swing.JLabel classicLabel;
    private javax.swing.JList classicList;
    private javax.swing.JLabel classicRatingLabel;
    private javax.swing.JList classicRatingList;
    private javax.swing.JLabel comedyLabel;
    private javax.swing.JList comedyList;
    private javax.swing.JLabel comedyRatingLabel;
    private javax.swing.JList comedyRatingList;
    private javax.swing.JLabel dramaLabel;
    private javax.swing.JList dramaList;
    private javax.swing.JLabel dramaRatingLabel;
    private javax.swing.JList dramaRatingList;
    private javax.swing.JLabel horrorLabel;
    private javax.swing.JList horrorList;
    private javax.swing.JLabel horrorRatingLabel;
    private javax.swing.JList horrorRatingList;
    private javax.swing.JButton importListButton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JList jList10;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane10;
    private javax.swing.JScrollPane jScrollPane11;
    private javax.swing.JScrollPane jScrollPane12;
    private javax.swing.JScrollPane jScrollPane13;
    private javax.swing.JScrollPane jScrollPane14;
    private javax.swing.JScrollPane jScrollPane15;
    private javax.swing.JScrollPane jScrollPane16;
    private javax.swing.JScrollPane jScrollPane17;
    private javax.swing.JScrollPane jScrollPane18;
    private javax.swing.JScrollPane jScrollPane19;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane20;
    private javax.swing.JScrollPane jScrollPane21;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JScrollPane jScrollPane6;
    private javax.swing.JScrollPane jScrollPane7;
    private javax.swing.JScrollPane jScrollPane8;
    private javax.swing.JScrollPane jScrollPane9;
    private javax.swing.JButton mainMenuButton;
    private javax.swing.JLabel mysteryLabel;
    private javax.swing.JList mysteryList;
    private javax.swing.JLabel mysteryRatingLabel;
    private javax.swing.JList mysteryRatingList;
    private javax.swing.JLabel romanticLabel;
    private javax.swing.JList romanticList;
    private javax.swing.JLabel romanticRatingLabel;
    private javax.swing.JList romanticRatingList;
    private javax.swing.JLabel sciFiLabel;
    private javax.swing.JList sciFiList;
    private javax.swing.JLabel sciFiRatingLabel;
    private javax.swing.JList sciFiRatingList;
    private javax.swing.JLabel sortedMoviesLabel;
    private javax.swing.JLabel thrillerLabel;
    private javax.swing.JList thrillerList;
    private javax.swing.JLabel thrillerRatingLabel;
    private javax.swing.JList thrillerRatingList;
    // End of variables declaration//GEN-END:variables
}
