/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package edu.hdsb.gwss.spencercook.ics3u.u7;

import java.io.File;
import javax.swing.DefaultListModel;
import nu.xom.Builder;
import nu.xom.Document;
import nu.xom.Element;
import nu.xom.Elements;

/**
 *
 * @author 1cookspe
 */
public class SortedMovies extends javax.swing.JFrame {

    /**
     * Creates new form SortedMovies
     */
    public SortedMovies() {
        initComponents();
        importData();
 
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        sortedMoviesLabel = new javax.swing.JLabel();
        importListButton = new javax.swing.JButton();
        actionLabel = new javax.swing.JLabel();
        mysteryLabel = new javax.swing.JLabel();
        comedyLabel = new javax.swing.JLabel();
        jScrollPane4 = new javax.swing.JScrollPane();
        actionList = new javax.swing.JList();
        jScrollPane5 = new javax.swing.JScrollPane();
        mysteryList = new javax.swing.JList();
        jScrollPane6 = new javax.swing.JScrollPane();
        comedyList = new javax.swing.JList();
        dramaLabel = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        dramaList = new javax.swing.JList();
        thrillerLabel = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        sciFiList = new javax.swing.JList();
        horrorLabel = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        horrorList = new javax.swing.JList();
        romanticLabel = new javax.swing.JLabel();
        jScrollPane7 = new javax.swing.JScrollPane();
        romanticList = new javax.swing.JList();
        classicLabel = new javax.swing.JLabel();
        jScrollPane8 = new javax.swing.JScrollPane();
        classicList = new javax.swing.JList();
        animatedLabel = new javax.swing.JLabel();
        jScrollPane9 = new javax.swing.JScrollPane();
        animatedList = new javax.swing.JList();
        sciFiLabel = new javax.swing.JLabel();
        jScrollPane10 = new javax.swing.JScrollPane();
        thrillerList = new javax.swing.JList();
        mainMenuButton = new javax.swing.JButton();
        addNewMovieButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        sortedMoviesLabel.setFont(new java.awt.Font("Bodoni MT Black", 0, 24)); // NOI18N
        sortedMoviesLabel.setText("Sorted Movies");

        importListButton.setFont(new java.awt.Font("Swis721 BlkEx BT", 0, 11)); // NOI18N
        importListButton.setText("Import List");
        importListButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                importListButtonActionPerformed(evt);
            }
        });

        actionLabel.setFont(new java.awt.Font("Impact", 0, 14)); // NOI18N
        actionLabel.setText("Action");

        mysteryLabel.setFont(new java.awt.Font("Impact", 0, 14)); // NOI18N
        mysteryLabel.setText("Mystery");

        comedyLabel.setFont(new java.awt.Font("Impact", 0, 14)); // NOI18N
        comedyLabel.setText("Comedy");

        jScrollPane4.setViewportView(actionList);

        jScrollPane5.setViewportView(mysteryList);

        jScrollPane6.setViewportView(comedyList);

        dramaLabel.setFont(new java.awt.Font("Impact", 0, 14)); // NOI18N
        dramaLabel.setText("Drama");

        jScrollPane1.setViewportView(dramaList);

        thrillerLabel.setFont(new java.awt.Font("Impact", 0, 14)); // NOI18N
        thrillerLabel.setText("Thriller");

        jScrollPane2.setViewportView(sciFiList);

        horrorLabel.setFont(new java.awt.Font("Impact", 0, 14)); // NOI18N
        horrorLabel.setText("Horror");

        jScrollPane3.setViewportView(horrorList);

        romanticLabel.setFont(new java.awt.Font("Impact", 0, 14)); // NOI18N
        romanticLabel.setText("Romantic");

        jScrollPane7.setViewportView(romanticList);

        classicLabel.setFont(new java.awt.Font("Impact", 0, 14)); // NOI18N
        classicLabel.setText("Classic");

        jScrollPane8.setViewportView(classicList);

        animatedLabel.setFont(new java.awt.Font("Impact", 0, 14)); // NOI18N
        animatedLabel.setText("Animated");

        jScrollPane9.setViewportView(animatedList);

        sciFiLabel.setFont(new java.awt.Font("Impact", 0, 14)); // NOI18N
        sciFiLabel.setText("Sci-Fi");

        jScrollPane10.setViewportView(thrillerList);

        mainMenuButton.setFont(new java.awt.Font("FreesiaUPC", 1, 24)); // NOI18N
        mainMenuButton.setText("Main Menu");
        mainMenuButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mainMenuButtonActionPerformed(evt);
            }
        });

        addNewMovieButton.setFont(new java.awt.Font("FreesiaUPC", 1, 24)); // NOI18N
        addNewMovieButton.setText("Add New Movie");
        addNewMovieButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addNewMovieButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(actionLabel)
                                        .addGap(30, 30, 30)))
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(54, 54, 54)
                                        .addComponent(mysteryLabel)
                                        .addGap(76, 76, 76)
                                        .addComponent(comedyLabel)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(dramaLabel)
                                        .addGap(33, 33, 33))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(31, 31, 31)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(importListButton)
                                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                .addGroup(layout.createSequentialGroup()
                                                    .addComponent(jScrollPane7, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                    .addComponent(jScrollPane8, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                .addGroup(layout.createSequentialGroup()
                                                    .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addGap(28, 28, 28)
                                                    .addComponent(jScrollPane6, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                        .addGap(31, 31, 31)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(jScrollPane9, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(39, 39, 39)
                                .addComponent(horrorLabel)
                                .addGap(79, 79, 79)
                                .addComponent(romanticLabel)
                                .addGap(75, 75, 75)
                                .addComponent(classicLabel)
                                .addGap(73, 73, 73)
                                .addComponent(animatedLabel)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(40, 40, 40)
                                .addComponent(thrillerLabel))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(20, 20, 20)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(29, 29, 29)
                                        .addComponent(sciFiLabel))
                                    .addComponent(jScrollPane10, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(mainMenuButton)
                        .addGap(92, 92, 92)
                        .addComponent(sortedMoviesLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(addNewMovieButton)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(addNewMovieButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(mainMenuButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(sortedMoviesLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(importListButton)
                .addGap(22, 22, 22)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(comedyLabel)
                    .addComponent(mysteryLabel)
                    .addComponent(actionLabel)
                    .addComponent(dramaLabel)
                    .addComponent(thrillerLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jScrollPane6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(26, 26, 26)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(sciFiLabel, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(horrorLabel)
                                .addComponent(romanticLabel)
                                .addComponent(classicLabel)
                                .addComponent(animatedLabel)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jScrollPane7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jScrollPane8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jScrollPane9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(jScrollPane10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(25, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void importListButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_importListButtonActionPerformed
        importData();

    }//GEN-LAST:event_importListButtonActionPerformed

    public void importData() {
        File file = new File("movieMadness.xml");
        Builder builder = new Builder();

        try {
            Document movieDocument = builder.build(file);
            Element movieRoot = movieDocument.getRootElement();
            Elements movies = movieRoot.getChildElements();

            DefaultListModel actionModel = new DefaultListModel();
            DefaultListModel mysteryModel = new DefaultListModel();
            DefaultListModel comedyModel = new DefaultListModel();
            DefaultListModel dramaModel = new DefaultListModel();
            DefaultListModel thrillerModel = new DefaultListModel();
            DefaultListModel horrorModel = new DefaultListModel();
            DefaultListModel romanticModel = new DefaultListModel();
            DefaultListModel classicModel = new DefaultListModel();
            DefaultListModel animatedModel = new DefaultListModel();
            DefaultListModel sciFiModel = new DefaultListModel();

            //GET VALUES FROM XML FILE
            for (int i = 0; i < movies.size(); i++) {
                if (movies.get(i).getFirstChildElement("movieGenre").getValue().equals("Action")) {
                    actionModel.addElement(movies.get(i).getFirstChildElement("movieName").getValue() + " - " + movies.get(i).getFirstChildElement("movieRating").getValue() + " STARS");
                } else if (movies.get(i).getFirstChildElement("movieGenre").getValue().equals("Mystery")) {
                    mysteryModel.addElement(movies.get(i).getFirstChildElement("movieName").getValue() + " - " + movies.get(i).getFirstChildElement("movieRating").getValue() + " STARS");
                } else if (movies.get(i).getFirstChildElement("movieGenre").getValue().equals("Comedy")) {
                    comedyModel.addElement(movies.get(i).getFirstChildElement("movieName").getValue() + " - " + movies.get(i).getFirstChildElement("movieRating").getValue() + " STARS");
                } else if (movies.get(i).getFirstChildElement("movieGenre").getValue().equals("Drama")) {
                    dramaModel.addElement(movies.get(i).getFirstChildElement("movieName").getValue() + " - " + movies.get(i).getFirstChildElement("movieRating").getValue() + " STARS");
                } else if (movies.get(i).getFirstChildElement("movieGenre").getValue().equals("Thriller")) {
                    thrillerModel.addElement(movies.get(i).getFirstChildElement("movieName").getValue() + " - " + movies.get(i).getFirstChildElement("movieRating").getValue() + " STARS");
                } else if (movies.get(i).getFirstChildElement("movieGenre").getValue().equals("Horror")) {
                    horrorModel.addElement(movies.get(i).getFirstChildElement("movieName").getValue() + " - " + movies.get(i).getFirstChildElement("movieRating").getValue() + " STARS");
                } else if (movies.get(i).getFirstChildElement("movieGenre").getValue().equals("Romantic")) {
                    romanticModel.addElement(movies.get(i).getFirstChildElement("movieName").getValue() + " - " + movies.get(i).getFirstChildElement("movieRating").getValue() + " STARS");
                } else if (movies.get(i).getFirstChildElement("movieGenre").getValue().equals("Classic")) {
                    classicModel.addElement(movies.get(i).getFirstChildElement("movieName").getValue() + " - " + movies.get(i).getFirstChildElement("movieRating").getValue() + " STARS");
                } else if (movies.get(i).getFirstChildElement("movieGenre").getValue().equals("Animated")) {
                    animatedModel.addElement(movies.get(i).getFirstChildElement("movieName").getValue() + " - " + movies.get(i).getFirstChildElement("movieRating").getValue() + " STARS");
                } else if (movies.get(i).getFirstChildElement("movieGenre").getValue().equals("Sci-Fi")) {
                    sciFiModel.addElement(movies.get(i).getFirstChildElement("movieName").getValue() + " - " + movies.get(i).getFirstChildElement("movieRating").getValue() + " STARS");
                }
            }

            actionList.setModel(actionModel);
            mysteryList.setModel(mysteryModel);
            comedyList.setModel(comedyModel);
            dramaList.setModel(dramaModel);
            animatedList.setModel(animatedModel);
            sciFiList.setModel(sciFiModel);
            classicList.setModel(classicModel);
            horrorList.setModel(horrorModel);
            romanticList.setModel(romanticModel);
            thrillerList.setModel(thrillerModel);

        } catch (Exception e) {
            e.printStackTrace();
        }
    }

    private void mainMenuButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mainMenuButtonActionPerformed
        new MovieMenu().setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_mainMenuButtonActionPerformed

    private void addNewMovieButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addNewMovieButtonActionPerformed
        new AddMovie().setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_addNewMovieButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(SortedMovies.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(SortedMovies.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(SortedMovies.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SortedMovies.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new SortedMovies().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel actionLabel;
    private javax.swing.JList actionList;
    private javax.swing.JButton addNewMovieButton;
    private javax.swing.JLabel animatedLabel;
    private javax.swing.JList animatedList;
    private javax.swing.JLabel classicLabel;
    private javax.swing.JList classicList;
    private javax.swing.JLabel comedyLabel;
    private javax.swing.JList comedyList;
    private javax.swing.JLabel dramaLabel;
    private javax.swing.JList dramaList;
    private javax.swing.JLabel horrorLabel;
    private javax.swing.JList horrorList;
    private javax.swing.JButton importListButton;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane10;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JScrollPane jScrollPane6;
    private javax.swing.JScrollPane jScrollPane7;
    private javax.swing.JScrollPane jScrollPane8;
    private javax.swing.JScrollPane jScrollPane9;
    private javax.swing.JButton mainMenuButton;
    private javax.swing.JLabel mysteryLabel;
    private javax.swing.JList mysteryList;
    private javax.swing.JLabel romanticLabel;
    private javax.swing.JList romanticList;
    private javax.swing.JLabel sciFiLabel;
    private javax.swing.JList sciFiList;
    private javax.swing.JLabel sortedMoviesLabel;
    private javax.swing.JLabel thrillerLabel;
    private javax.swing.JList thrillerList;
    // End of variables declaration//GEN-END:variables
}
